### ISSUE TITLE
inconsistency in manifest tags

### ISSUE THREAD

**Issue by masterkain** [drone-plugins/drone-docker#254] opened 2019-11-08 19:58 UTC
getting spammed by flux about this tag:

```
│ ts=2019-11-08T19:56:23.454636483Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/drone/drone auth={map[]} warn="manifest for tag 1.0.0-rc.6 missing in repository docker.io/drone/drone" impact="flux will fail to auto-r
│ elease workloads with matching images, ask the repository administrator to fix the inconsistency"

```

**Comment by ashwilliams1** [comment] 2019-11-08 20:12
this does not appear to be related to this plugin.

this also looks like a duplicate of https://github.com/drone/drone/issues/2868

**Closed by ashwilliams1** 2019-11-08 20:12 UTC
