### ISSUE TITLE
Tagging when git commit starts with leading 0s causes issues.

### ISSUE THREAD

**Issue by edwinavalos** [drone-plugins/drone-docker#113] opened 2017-03-06 14:23 UTC
We noticed that our kubernetes deployments weren't able to find the image we had tagged with just ${DRONE_COMMIT:0:8} and "prerelease" string.

With the following commit in DRONE_COMMIT value "09334553" the plugin tries to tag the image as follows:

+ /usr/local/bin/docker tag 09334553bd6437f70a5a3c5ad2830c16c28e4f5a gcr.io/xxxxxx/clouddriver:9.334553e+06
Error parsing reference: "gcr.io/xxxxxx/clouddriver:9.334553e+06" is not a valid repository/tag.

This is on a drone server that has the new secret interpolation installed on it so it might be an issue with ${DRONE_COMMIT:0:8} instead of $DRONE_COMMIT:0:8 I will try and track that down, it's a bit of a roulette trying to recreate the issue of course.

If I can find the bug in the drone-docker code I will patch it.

**Comment by bradrydzewski** [comment] 2017-03-06 16:09
I don't think the issue is with the docker plugin. I think it is with how the yaml parser converts numbers to string. Probably here https://github.com/drone/drone/blob/master/yaml/transform/util.go#L38 ... I believe it is possible to sprintf float values without using scientific notation. On phone though, so will have to check later.

**Comment by patrickdappollonio** [comment] 2017-09-14 20:48
Ran into the same issue. Tried tagging a docker container as `v1.${DRONE_BUILD_NUMBER}` where `$DRONE_BUILD_NUMBER` was `120`, but it handled it as `12`.

**Comment by tboerger** [comment] 2017-09-14 22:15
If you quote the tag with single quotes this won't happen.

**Comment by patrickdappollonio** [comment] 2017-09-14 22:21
You mean `'${DRONE_COMMIT:0:8}'`? I'll try that...

**Comment by tboerger** [comment] 2017-09-15 06:26
Exactly, this enforces the yaml parser to keep it as a string

**Comment by tboerger** [comment] 2019-02-10 18:11
Just related to yaml parsing, closing as it's not related to this plugin.

**Closed by tboerger** 2019-02-10 18:11 UTC
