### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by strahe** [drone-plugins/drone-docker#83] opened 2016-09-19 05:47 UTC
Hi,when i use drone to build docker images, i  got the error:
```
[info] Pulling image plugins/drone-git:latest
Drone Git Plugin built from 43dcd64
$ git init
Initialized empty Git repository in /drone/src/114.55.23.12/strahe/drone_test/.git/
$ git remote add origin http://114.55.23.12:30080/strahe/drone_test.git
$ git fetch --no-tags origin +refs/heads/master:
From http://114.55.23.12:30080/strahe/drone_test
* branch            master     -> FETCH_HEAD
* [new branch]      master     -> origin/master
$ git reset --hard -q 050be0ea7cfd60713756d030b1dcb5b7c16ba94b
[info] Pulling image plugins/drone-docker:latest
time="2016-09-19T03:58:46Z" level=fatal msg="no such file or directory" 
[info] build failed (exit code 1)
```
any ideas?

**Comment by tboerger** [comment] 2016-09-19 07:12
You should provide a `.drone.yml` so that we are able to reproduce it.

**Comment by strahe** [comment] 2016-09-19 07:18
@tboerger 
```
build:
    image: python:latest

publish:
    docker:
        username: ...
        password: ...
        email: ...
        repo: privately registry
        tag: latest
        file: Dockerfile
```

**Comment by tboerger** [comment] 2016-09-19 07:21
And the `Dockerfile` does exist in your project root?

**Comment by strahe** [comment] 2016-09-19 07:24
@tboerger yes

**Comment by tboerger** [comment] 2016-09-19 07:31
@bradrydzewski any idea where else this can come from?

@strahe can you debug it locally like https://github.com/drone-plugins/drone-docker/tree/release/0.4#example please?

**Comment by strahe** [comment] 2016-09-19 08:07
@tboerger 
I try https://github.com/drone-plugins/drone-docker/tree/release/0.4#example , but i get another error：
```
Drone Docker Plugin built at 2016-07-29 06:41:09 UTC
panic: invalid character '"' after object key:value pair

goroutine 1 [running]:
panic(0x52a9e0, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/drone-plugins/drone-docker/vendor/github.com/drone/drone-plugin-go/plugin.MustParse()
        /drone/src/github.com/drone-plugins/drone-docker/vendor/github.com/drone/drone-plugin-go/plugin/param.go:129 +0x59
main.main()
        /drone/src/github.com/drone-plugins/drone-docker/main.go:59 +0x4d1
```

**Comment by tboerger** [comment] 2016-09-19 08:13
Sorry, the example is missing a `,` behind the line `"author_email": "john.smith@gmail.com"`

**Comment by strahe** [comment] 2016-09-19 09:16
I had change the example "vargs" right, but i always get `Login failed.` , elsewhere i need to amend it?
i use registry v2.

**Comment by tboerger** [comment] 2016-09-19 10:50
Have you tried the documented troubleshooting?

**Comment by strahe** [comment] 2016-09-20 08:00
@tboerger sorry，this is my first time using drone，here are all the debugging information I got.
```
root@iZ236nu15v3Z:~# docker run -i --privileged -v $(pwd):/drone/src plugins/drone-docker <<EOF
> {
>     "repo": {
>         "clone_url": "git://github.com/drone/drone",
>         "owner": "drone",
>         "name": "drone",
>         "full_name": "drone/drone"
>     },
>     "system": {
>         "link_url": "https://beta.drone.io"
>     },
>     "build": {
>         "number": 22,
>         "status": "success",
>         "started_at": 1421029603,
>         "finished_at": 1421029813,
>         "message": "Update the Readme",
>         "author": "johnsmith",
>         "author_email": "john.smith@gmail.com"
>         "event": "push",
>         "branch": "master",
>         "commit": "436b7a6e2abaddfd35740527353e78a227ddcb2c",
>         "ref": "refs/heads/master"
>     },
>     "workspace": {
>         "root": "/drone/src",
>         "path": "/drone/src/github.com/drone/drone"
>     },
>     "vargs": {
>         "username": "...",
>         "password": "...",
>         "email": "...",
>         "registry": "...",
>         "repo": "...",
>         "storage_driver": "aufs"
>     }
> }
> EOF
time="2016-09-20T07:53:54Z" level=fatal msg="no such file or directory"

root@iZ236nu15v3Z:~# docker logs 96756c996024
time="2016-09-20T07:53:54Z" level=fatal msg="no such file or directory"
```

**Comment by tboerger** [comment] 2016-09-20 08:53
https://github.com/drone-plugins/drone-docker/blob/release/0.4/DOCS.md#troubleshooting there you can see the troubleshooting section of the docs.

**Comment by tboerger** [comment] 2016-09-20 08:57
Even with the example I'm not able to reproduce it.

```
# docker run -i --privileged -v $(pwd):/drone/src plugins/drone-docker <<EOF
> {
>     "repo": {
>         "clone_url": "git://github.com/drone/drone",
>         "owner": "drone",
>         "name": "drone",
>         "full_name": "drone/drone"
>     },
>     "system": {
>         "link_url": "https://beta.drone.io"
>     },
>     "build": {
>         "number": 22,
>         "status": "success",
>         "started_at": 1421029603,
>         "finished_at": 1421029813,
>         "message": "Update the Readme",
>         "author": "johnsmith",
>         "author_email": "john.smith@gmail.com",
>         "event": "push",
>         "branch": "master",
>         "commit": "436b7a6e2abaddfd35740527353e78a227ddcb2c",
>         "ref": "refs/heads/master"
>     },
>     "workspace": {
>         "root": "/drone/src",
>         "path": "/drone/src/github.com/drone/drone"
>     },
>     "vargs": {
>         "username": "kevinbacon",
>         "password": "pa$$word",
>         "email": "foo@bar.com",
>         "repo": "foo/bar",
>         "storage_driver": "aufs"
>     }
> }
> EOF
Drone Docker Plugin built at 2016-07-29 06:41:09 UTC
$ /usr/bin/docker daemon -g /drone/docker -s aufs
Login failed.
```

**Comment by strahe** [comment] 2016-09-20 09:14
@tboerger 
```
[info] Pulling image plugins/drone-docker:latest
time="2016-09-20T09:10:08Z" level=debug msg="Launch config dockerlaunch.Config{Fork:false, PidOne:false, CommandName:\"\", DnsConfig:netconf.DnsConfig{Override:false, Nameservers:[]string(nil), Search:[]string(nil)}, BridgeName:\"\", BridgeAddress:\"\", BridgeMtu:0, CgroupHierarchy:map[string]string(nil), LogFile:\"\", NoLog:false, EmulateSystemd:false, NoFiles:0x0, Environment:[]string(nil), GraphDirectory:\"\"}" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting devtmpfs /dev devtmpfs " 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /dev/pts devpts " 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /proc proc " 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /run tmpfs " 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys sysfs " 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/cgroup tmpfs " 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/selinux selinuxfs " 
time="2016-09-20T09:10:08Z" level=debug msg="Unable to mount none /sys/fs/selinux selinuxfs : mkdir /sys/fs/selinux: read-only file system" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: #subsys_name\thierarchy\tnum_cgroups\tenabled" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: cpuset\t2\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: cpu\t3\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: cpuacct\t3\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: memory\t0\t1\t0" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: devices\t4\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: freezer\t5\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: net_cls\t6\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: blkio\t7\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: perf_event\t8\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="/proc/cgroups: net_prio\t6\t17\t1" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/cgroup/blkio cgroup blkio" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/cgroup/perf_event cgroup perf_event" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/cgroup/cpuset cgroup cpuset" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/cgroup/cpu,cpuacct cgroup cpu,cpuacct" 
time="2016-09-20T09:10:08Z" level=debug msg="Creating /sys/fs/cgroup/memory" 
time="2016-09-20T09:10:08Z" level=debug msg="Mounting none /sys/fs/cgroup/memory cgroup memory" 
time="2016-09-20T09:10:08Z" level=fatal msg="no such file or directory" 
[info] build failed (exit code 1)
```

**Comment by tboerger** [comment] 2016-09-20 12:58
Look at the last example of known issues of https://github.com/drone-plugins/drone-docker/blob/master/DOCS.md

After applying that this should be solved. I will close this issue for now since this is a known issue and we already provide a solution. Please comment if something is still unclear.

**Closed by tboerger** 2016-09-20 12:58 UTC

**Comment by EvertonSA** [comment] 2020-04-08 13:11
@tboerger  The link is broken

**Comment by tboerger** [comment] 2020-04-08 13:53
This link is already 4 years, so what do you expect?
